apiVersion: v1
kind: ConfigMap
metadata:
  name: queue-service-config
  labels:
    app: queue-service
data:
  RESOURCE_LOCKER_URL: {{ include "services-chart.resourceLockerUrl" . }}
  RESOURCE_LOCKER_TOKEN: {{ include "services-chart.resourceLockerToken" . }}